"""init

Revision ID: 47fc847fce7d
Revises: 
Create Date: 2022-01-14 13:57:33.942514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fc847fce7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind speed', sa.Float(), nullable=True),
    sa.Column('wind direction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', name=op.f('pk_weather')),
    sa.UniqueConstraint('time', name=op.f('uq_weather_time'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
