"""init

Revision ID: ccdb589f8b8f
Revises: 
Create Date: 2022-01-05 10:43:57.727339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdb589f8b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SQM',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', name=op.f('pk_SQM'))
    )
    op.create_index('timestamp', 'SQM', ['time'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('timestamp', table_name='SQM')
    op.drop_table('SQM')
    # ### end Alembic commands ###
